
name: PixelLOG
version: 0.0.1
main: nmil.mceeg.plugin.MainPlugin
commands:
  pl-start:
    description: start collecting logs on command sender.
    usage: /pr-start
  pl-stop:
    description: stop collecting logs on command sender.
    usage: /pr-stop
  pl-start-op:
    description: start collecting logs on an online player, OP only.
    usage: /pl-start-op [username]
  pl-stop-op:
    description: stop collecting logs on an online player, OP only.
    usage: /pl-stop-op [username]
  pl-version:
    description: A test command for the plugin.

api-version: 1.20